"""change user info column

Revision ID: 4d85b69aa23e
Revises: 8d61227b13cf
Create Date: 2020-02-10 17:03:37.795033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d85b69aa23e'
down_revision = '8d61227b13cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('role', sa.Integer(), nullable=True))
    op.drop_column('user_info', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('admin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user_info', 'role')
    # ### end Alembic commands ###
