"""modify tables

Revision ID: 20bad2071a41
Revises: e6f36a6248e3
Create Date: 2020-02-19 11:58:58.162791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20bad2071a41'
down_revision = 'e6f36a6248e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remain_vacation', sa.Column('user_id', sa.String(length=30), nullable=False))
    op.drop_index('google_id', table_name='remain_vacation')
    op.create_foreign_key(None, 'remain_vacation', 'user', ['user_id'], ['google_id'])
    op.drop_column('remain_vacation', 'google_id')
    op.add_column('used_vacation', sa.Column('user_id', sa.String(length=30), nullable=False))
    op.create_foreign_key(None, 'used_vacation', 'user', ['user_id'], ['google_id'])
    op.drop_column('used_vacation', 'google_id')
    op.create_unique_constraint('unique_user_constraint', 'user', ['google_id', 'en_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_constraint', 'user', type_='unique')
    op.add_column('used_vacation', sa.Column('google_id', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'used_vacation', type_='foreignkey')
    op.drop_column('used_vacation', 'user_id')
    op.add_column('remain_vacation', sa.Column('google_id', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'remain_vacation', type_='foreignkey')
    op.create_index('google_id', 'remain_vacation', ['google_id'], unique=True)
    op.drop_column('remain_vacation', 'user_id')
    # ### end Alembic commands ###
