"""empty message

Revision ID: cd322ae2dc34
Revises: b214a1740572
Create Date: 2020-01-17 11:09:15.051122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd322ae2dc34'
down_revision = 'b214a1740572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('test', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'test')
    # ### end Alembic commands ###
